'use client';

import React from 'react';
import { useRevenueCat } from '@/hooks/useRevenueCat';

/**
 * A simple button to redirect the user to their Customer Center 
 * (Stripe Billing Portal) generated by RevenueCat Web SDK.
 */
export default function CustomerCenterButton() {
    const { customerInfo, isPro, loading } = useRevenueCat();

    if (loading) {
        return <span className="text-sm text-[#0C4A6E]/50">読み込み中...</span>;
    }

    // Only show manage button if they have an active Customer Info and a URL
    // The 'managementURL' property provides a direct link to the Stripe Customer Portal
    const managementURL = customerInfo?.managementURL;

    if (!managementURL) {
        return null; // Don't show if they don't have a subscription management portal
    }

    return (
        <div className="flex flex-col space-y-2">
            <a
                href={managementURL}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex cursor-pointer items-center justify-center rounded-lg border border-sky-200 bg-[#F0F9FF] px-4 py-2 text-sm font-semibold text-[#0EA5E9] transition-all duration-200 hover:border-[#0EA5E9] hover:bg-white"
            >
                サブスクリプションを管理する
            </a>
            {isPro && (
                <span className="text-center text-xs font-semibold text-[#0EA5E9]">
                    ✓ Yarikiru Pro 有効
                </span>
            )}
        </div>
    );
}
